class_name GameAudio
extends Node
## Polyphonic SFX player + looping ambient wind. Streams are loaded from
## res://audio/*.wav (generated by tools/gen_audio.py).

const SOUNDS := ["shot_rifle", "reload", "hurt", "impact", "enemy_die",
	"boss_roar", "wave_start", "dodge", "click", "amb_wind"]

var _streams: Dictionary = {}
var _player: AudioStreamPlayer
var _amb: AudioStreamPlayer

func _ready() -> void:
	for s in SOUNDS:
		var path := "res://audio/%s.wav" % s
		if ResourceLoader.exists(path):
			_streams[s] = load(path)
	_player = AudioStreamPlayer.new()
	_player.stream = AudioStreamPolyphonic.new()
	_player.max_polyphony = 16
	_player.volume_db = -3.0
	add_child(_player)
	_amb = AudioStreamPlayer.new()
	if _streams.has("amb_wind"):
		var wind: AudioStreamWAV = _streams["amb_wind"]
		wind.loop_mode = AudioStreamWAV.LOOP_FORWARD
		wind.loop_begin = 0
		wind.loop_end = wind.data.size() / 2
		_amb.stream = wind
	_amb.volume_db = -15.0
	add_child(_amb)

func play(sound: String, vol_db := 0.0) -> void:
	if not _streams.has(sound):
		return
	if not _player.playing:
		_player.play()
	var pb := _player.get_stream_playback() as AudioStreamPlaybackPolyphonic
	if pb != null:
		pb.play_stream(_streams[sound], 0.0, vol_db, randf_range(0.94, 1.06))

func start() -> void:
	# Called after the first user gesture (audio unlock).
	if not _player.playing:
		_player.play()
	if _streams.has("amb_wind") and not _amb.playing:
		_amb.play()
